import { X, Search, Plus, MoreHorizontal, Pencil, Trash2 } from 'lucide-react';

export function PageHeader({eyebrow='Commerce',title,description,actions}){return <div className="mb-7 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.18em] text-neutral-400">{eyebrow}</p><h1 className="text-2xl font-semibold tracking-[-.03em] text-black sm:text-3xl">{title}</h1>{description&&<p className="mt-2 max-w-2xl text-sm leading-6 text-neutral-500">{description}</p>}</div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</div>}
export function Status({children}){const map={Published:'bg-emerald-50 text-emerald-700',Paid:'bg-emerald-50 text-emerald-700',Active:'bg-emerald-50 text-emerald-700',Live:'bg-emerald-50 text-emerald-700',Delivered:'bg-emerald-50 text-emerald-700',Processing:'bg-amber-50 text-amber-700',Confirmed:'bg-blue-50 text-blue-700',Shipped:'bg-violet-50 text-violet-700',Scheduled:'bg-blue-50 text-blue-700',Draft:'bg-neutral-100 text-neutral-600',Inactive:'bg-neutral-100 text-neutral-600',Cancelled:'bg-red-50 text-red-700',Refunded:'bg-red-50 text-red-700','Out of stock':'bg-red-50 text-red-700','Low stock':'bg-amber-50 text-amber-700'};return <span className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${map[children]||'bg-neutral-100 text-neutral-600'}`}>{children}</span>}
export function SearchBox({value,onChange,placeholder='Search...'}){return <div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-neutral-400"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="input pl-9"/></div>}
export function Modal({open,onClose,title,children,wide=false}){if(!open)return null;return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/55 p-4 backdrop-blur-sm" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className={`max-h-[92vh] w-full overflow-y-auto rounded-3xl bg-[#f8f8f6] p-5 shadow-2xl ${wide?'max-w-4xl':'max-w-xl'}`}><div className="mb-5 flex items-center justify-between"><h3 className="text-lg font-semibold tracking-tight">{title}</h3><button onClick={onClose} className="rounded-xl p-2 hover:bg-black/5"><X className="h-5 w-5"/></button></div>{children}</div></div>}
export function Empty({title='Nothing here',text='No matching records found.'}){return <div className="p-10 text-center"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-neutral-500">{text}</p></div>}
export function AddButton({children,onClick}){return <button className="btn-dark" onClick={onClick}><Plus className="h-4 w-4"/>{children}</button>}
export function KpiCard({label,value,change,icon:Icon,meta}){return <div className="card p-5"><div className="flex items-start justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-black text-white"><Icon className="h-4 w-4"/></div>{change&&<span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${change.startsWith('-')?'bg-red-50 text-red-600':'bg-emerald-50 text-emerald-700'}`}>{change}</span>}</div><p className="mt-5 text-sm text-neutral-500">{label}</p><p className="mt-1 text-2xl font-semibold tracking-[-.04em]">{value}</p>{meta&&<p className="mt-2 text-xs text-neutral-400">{meta}</p>}</div>}
export function RowActions({onEdit,onDelete}){return <div className="flex justify-end gap-1"><button aria-label="Edit" title="Edit" onClick={onEdit} className="rounded-lg px-2.5 py-1.5 text-xs font-semibold hover:bg-neutral-100"><Pencil size={17}/></button><button aria-label="Delete" title="Delete" onClick={onDelete} className="rounded-lg px-2.5 py-1.5 text-xs font-semibold text-red-600 hover:bg-red-50"><Trash2 size={17}/></button></div>}
export function MiniMenuButton(){return <button className="rounded-lg p-2 hover:bg-neutral-100"><MoreHorizontal className="h-4 w-4"/></button>}

export function TableLoading({columns=8}){return <tr><td colSpan={columns} className="p-6"><div role="status" aria-label="Loading records" className="space-y-3 motion-safe:animate-pulse">{[0,1,2].map(i=><div key={i} className="h-5 rounded bg-neutral-200"/>)}<span className="sr-only">Loading records…</span></div></td></tr>}
